#!/usr/bin/env node

if(typeof require('module')._extensions['.coffee']==='undefined'){
  // Avoid conflicts with another version
  require('coffee-script/register');
}
var nicolive= require('./lib/nicolive');

if(module.parent===null){
  process.on('uncaughtException',function(error){
    throw error;
    process.exit(1);
  });
  
  nicolive.cli(process.argv);
}

module.exports= nicolive;